In [11]:
import numpy as np
import pandas as pd

In [21]:
data=pd.read_csv(r'C:\Users\2meen\Downloads\archive (2)\FullData.csv')
data

,SEQN,depression,gender,age,race,citizenship,education_level,marital_status,household_size,pregnant,...,Rx_INSULIN REGULAR,Rx_days_INSULIN REGULAR,Rx_MEMANTINE,Rx_days_MEMANTINE,Rx_DIPHENHYDRAMINE,Rx_days_DIPHENHYDRAMINE,Rx_MINOCYCLINE,Rx_days_MINOCYCLINE,Rx_METHOCARBAMOL,Rx_days_METHOCARBAMOL
0,31131,Not Depressed,1,44,Black,Citizen,4,Married,4,No,...,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
1,31132,Not Depressed,0,70,White,Citizen,5,Married,2,Missing,...,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
2,31134,Not Depressed,0,73,White,Citizen,3,Married,2,Missing,...,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
3,31139,Not Depressed,1,18,Other Hispanic,Citizen,0,Never Married,3,No,...,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
4,31143,Not Depressed,0,19,White,Citizen,0,Never Married,3,Missing,...,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36254,102949,Not Depressed,0,33,White,Citizen,3,Partner,5,Missing,...,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
36255,102952,Not Depressed,1,70,Other and Multiracial,Citizen,3,Married,2,Missing,...,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
36256,102953,Not Depressed,0,42,Mexican,Not Citizen,3,Separated,1,Missing,...,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
36257,102954,Not Depressed,1,41,Black,Citizen,5,Never Married,7,No,...,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
36258,102956,Not Depressed,0,38,White,Citizen,4,Divorced,5,Missing,...,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0

In [37]:
A=data['depression']
from numpy import array
from sklearn.preprocessing import LabelEncoder
label_encoder=LabelEncoder()
depression_labels=label_encoder.fit_transform(array(A))
print(depression_labels[30:40])
#Not depressed is 1, and depressed is 0
data['depression_labels']=depression_labels
data.head(5)

[1 1 1 1 1 1 1 0 1 1]

,SEQN,depression,gender,age,race,citizenship,education_level,marital_status,household_size,pregnant,...,Rx_days_INSULIN REGULAR,Rx_MEMANTINE,Rx_days_MEMANTINE,Rx_DIPHENHYDRAMINE,Rx_days_DIPHENHYDRAMINE,Rx_MINOCYCLINE,Rx_days_MINOCYCLINE,Rx_METHOCARBAMOL,Rx_days_METHOCARBAMOL,depression_labels
0,31131,Not Depressed,1,44,Black,Citizen,4,Married,4,No,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,1
1,31132,Not Depressed,0,70,White,Citizen,5,Married,2,Missing,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,1
2,31134,Not Depressed,0,73,White,Citizen,3,Married,2,Missing,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,1
3,31139,Not Depressed,1,18,Other Hispanic,Citizen,0,Never Married,3,No,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,1
4,31143,Not Depressed,0,19,White,Citizen,0,Never Married,3,Missing,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,1